core/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("video/", videopage, name="video"),
    path("courses/", coursepage, name="coursepage"),
    path("course/<str:slug>", course, name="course"),
    path("", homepage, name="home"),
]

embed_video_pr/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/models.py
from django.db import models
from embed_video.fields import EmbedVideoField

# Create your models here.


class Course(models.Model):
    name = models.CharField(max_length=50, null=True, unique=True)
    slug = models.CharField(max_length=50, null=True)
    description = models.CharField(max_length=200, null=True)
    price = models.IntegerField(null=False)
    discount = models.IntegerField(null=False, default=0)
    active = models.BooleanField(default=False)
    thumbnail = models.ImageField(upload_to="files/thumbnail")
    date = models.DateTimeField(auto_now_add=True)
    resource = models.FileField(upload_to="files/resource")
    length = models.IntegerField(null=False)

    def __str__(self):
        return self.name


class CourseProperty(models.Model):
    description = models.CharField(max_length=100, null=False)
    course = models.ForeignKey(Course, null=False, on_delete=models.CASCADE)

    class Meta:
        abstract = True


class Tag(CourseProperty):
    pass


class Prerequisite(CourseProperty):
    pass


class Learning(CourseProperty):
    pass


class Video(models.Model):
    title = models.CharField(max_length=100, null=False)
    course = models.ForeignKey(Course, null=False, on_delete=models.CASCADE)
    serial_number = models.IntegerField(null=False)
    added = models.DateTimeField(auto_now_add=True)
    url = EmbedVideoField()
    is_preview = models.BooleanField(default=False)

    def __str__(self):
        return str(self.title)

    class Meta:
        ordering = ["-added"]

core/views.py
from django.shortcuts import render
from .models import *

# Create your views here.


def homepage(request):
    return render(request, "index.html")


def coursepage(request):
    courses = Course.objects.all()
    return render(request, "courses/index.html", {"courses": courses})


def course(request, slug):
    course = Course.objects.get(slug=slug)
    serial_number = request.GET.get("lecture")
    if serial_number is None:
        serial_number = 1
    video = Video.objects.get(serial_number=serial_number, course=course)
    context = {"course": course, "video": video}
    return render(request, "courses/page.html", context=context)


def videopage(request):
    videos = Video.objects.all()
    return render(request, "videos/index.html", {"videos": videos})

core/templates/courses/index.html
{% extends "base.html" %}
{% load course_custom_tags %}
{% block content %}

<style>
    .price {
        font-size: 20px;
    }
</style>

<div class="container">
    <h1 class="display-1">Courses</h1>
    <br>
    <div class="row">
        {% for course in courses %}
        <div class="col mx-auto">
            <div class="card mx-auto" style="width: 18rem;">
                <img class="card-img-top" src="{{course.thumbnail.url}}" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">{{course.name}}</h5>
                    <p class="card-text m-0 p-0">
                        Save {{course.discount}}%
                        <br>
                        <span class="price">
                            <del>{{course.price|rupee}}</del>
                            &nbsp;

                            <span>{% cal_sellprice course.price course.discount as value %} {{value|rupee}}</span>
                        </span>

                    </p>
                </div>
                
                <!-- Card Footer -->

                <div class="card-footer p-0">


                    <div class="row no-gutters">
                        <div class="col border-right">
                            <a href="#" class="btn btn-light btn-block">Enroll Now</a>
                        </div>
                        <div class="col">
                            <a href="/course/{{course.slug}}" class="btn btn-light  btn-block">Show More</a>
                        </div>
                    </div>

                </div>
                
            </div>
        </div>
        {% endfor %}
    </div>
</div>

  
  <br>

{% endblock %}

core/templates/courses/page.html
{% extends "base.html" %}
{% load embed_video_tags %}
{% load static %}
{% load course_custom_tags %}


{%block title%}
Courses
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'courses/css/scrollbar.css'%}">
<link rel="stylesheet" href="{% static 'courses/css/common.css'%}">

{% endblock %}

{% block js %}
<script src="{% static 'courses/js/course_page.js' %}"></script>
{% endblock %}

{% block content %}

<style>
    .no-preview{
        cursor: not-allowed;
    }   
    a:hover{
        text-decoration: none;
    }

    a{
        color: rgb(61, 59, 59);
    }

    .active-video-link{
        color: rgb(206, 202, 196);
    }

    .active-video-link:hover{
        text-decoration: none;
        color: rgb(255, 255, 255);
    }
    
</style>
   
<div class="">
    <p hidden>Selected Course: {{course.video_set.all}}</p>

    <div>
        <br>
        <div class="card p-3">
            <div class="row">
 
               <!-- YouTube Player -->

                <div class="col">
                    <div id='player' class="mx-auto">
                        {% for video in course.video_set.all %}
                          <li class="list-group-item active">{% video video.url '100%x500' %}</li>
                        {% endfor %}
                    </div>
                </div>

               <!-- Lecture List -->

                <div class="col-3">
                    <div class="border">
                        <ul id='video_list' class="list-group overflow-y-scroll">
                            {% for video in course.video_set.all %}
                            <li 
                              class="list-group-item">
                              <a href="?lecture={{video.serial_number}}">{{video}}</a>
                            </li>
                            {% endfor %}
                          </ul>
                    </div>
                </div>

            </div>
        </div>
        

        <!-- course details -->
        <div class="mt-3">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">{{course.name}}</h5>
                    <p class="card-text">{{course.description}}</p>
                </div>
            </div>
        </div>

        <!-- Prerequite -->
        <div class="mt-3">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Prerequisite</h5>
                    <p class="card-text">
                    <ol>
                        {% for pre in course.prerequisite_set.all %}
                        <li class="">{{pre.description}}</li>
                        {% endfor %}
                    </ol>
                    </p>
                </div>
            </div>
        </div>

        <!-- Learnings -->
        <div class="mt-3">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Learnings</h5>
                    <p class="card-text">
                    <ol>
                        {% for l in course.learning_set.all %}
                        <li class="">{{l.description}}</li>
                        {% endfor %}
                    </ol>
                    </p>
                </div>
            </div>
        </div>

        <!-- learning end -->
        <br>
        <br>
        <br>
    </div>
</div>



{% endblock %}

core/templates/videos/index.html
{% extends "base.html" %}
{% load embed_video_tags %}

{% block content %}
  <h1>Video Lectures</h1>
  {% for item in videos %}
    {% video item.url 'large' %}
    <h3>{{item.title}}</h3>

  {% endfor %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {%  endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    {% block css %}
    {% endblock %}
</head>
<body>
    <div class="">
        <!-- NavBar Section -->
        <nav class="navbar bg-white navbar-expand-sm sticky-top fw-bold">
            <div class="container-fluid">
                <a href="#" class="navbar-brand fs-2">L<span class="text-success">B</span>YH-CBSE</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#lbyh-navbar" aria-controls="lbyh-navbar" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>                       
                <div class="collapse navbar-collapse" id="lbyh-navbar">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item dropdown mt-1">
                            <a class="nav-item btn btn-outline-success dropdown-toggle" href="#" id="coursesDropdown" role="button"
                                data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Courses
                            </a>
                            <ul class="dropdown-menu">
                                <li class="dropdown-submenu">
                                    <a class="dropdown-item dropdown-toggle" href="#">Class 9th</a>
                                    <ul class="dropdown-menu">
                                        <a class="dropdown-item" href="#">Subcourse 1.1</a>
                                        <a class="dropdown-item" href="#">Subcourse 1.2</a>
                                        <a class="dropdown-item" href="#">Subcourse 1.3</a>
                                    </ul>
                                </li>
                                <div class="dropdown-divider"></div>
                                <li class="dropdown-submenu">
                                    <a class="dropdown-item dropdown-toggle" href="#">Class 10th</a>
                                    <ul class="dropdown-menu">
                                        <a class="dropdown-item" href="#">Subcourse 1.1</a>
                                        <a class="dropdown-item" href="#">Subcourse 1.2</a>
                                        <a class="dropdown-item" href="#">Subcourse 1.3</a>
                                    </ul>
                                </li>
                                <div class="dropdown-divider"></div>
                                <li class="dropdown-submenu">
                                    <a class="dropdown-item dropdown-toggle" href="#">Class 11th</a>
                                    <ul class="dropdown-menu">
                                        <a class="dropdown-item" href="#">Subcourse 1.1</a>
                                        <a class="dropdown-item" href="#">Subcourse 1.2</a>
                                        <a class="dropdown-item" href="#">Subcourse 1.3</a>
                                    </ul>
                                </li>
                                <div class="dropdown-divider"></div>
                                <li class="dropdown-submenu">
                                    <a class="dropdown-item dropdown-toggle" href="#">Class 12th</a>
                                    <ul class="dropdown-menu">
                                        <a class="dropdown-item" href="#">Subcourse 1.1</a>
                                        <a class="dropdown-item" href="#">Subcourse 1.2</a>
                                        <a class="dropdown-item" href="#">Subcourse 1.3</a>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-link mt-1 px-lg-5">
                            <a href="#" class="text-decoration-none text-success">Contact Us</a>
                        </li>
                        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-1 border-bottom"></div>
                        <br>
                        <li class="nav-item px-3">
                            <button class="btn btn-success btn-lg">Login/Register</button>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        <hr>

        <!-- Content Section -->

        <div class="container-xxl">
            {% block content %}
         
            {% endblock %}
        </div>

        <hr>

        <!-- Footer Section  -->
        
        <footer>
            <div class="cus_upper-row">
                <div class="cus_left-side">
                    <p class="fw-bold">Subscribe</p>
                </div>
                <div class="cus_right-side">
                    <div class="cus_input-container">
                        <input type="email" id="emailInput" placeholder="Enter your Email Address" />
                        <button type="submit" onclick="subscribe()"></button>
                    </div>
                    <p class="subscribe-message">Subscribe to stay tuned for new design and latest updates. Let's do it!</p>
                    <p id="success" class="success">Successfully subscribed to LBYH</p>
                </div>
            </div>
            <div class="cus_separator"></div>
            <div class="cus_container">
                <div class="cus_row">
                      <div class="cus_col" id="company">
                          <img src="../static/images/horizen.png" alt="" class="brand_logo">
                          <h2>L<span class="text-success">B</span>YH-CBSE</h2>
                          <div class="social">
                            <a href="#" class="text-center"><i class="fab fa-facebook text-primary"></i></a>
                            <a href="#" class="text-center"><i class="fab fa-youtube text-danger"></i></a>
                            <a href="#" class="text-center"><i class="fab fa-twitter text-info"></i></a>
                            <a href="#" class="text-center"><i class="fab fa-linkedin text-primary"></i></a>
                          </div>
                          <p>Follow us.</p>
                      </div>
                      <div class="cus_col" id="Company">
                         <h3>Company&nbsp;<span class="fas fa-caret-down" style="color: aliceblue;"></span></h3>
                          <div class="links msab">
    
                            <a href="#">About Us</a>
                            <a href="#">Careers</a>
                            <a href="#">Updates</a>
                            <a href="#">Teams</a>
                         </div>
                        </div>
                        <div class="cus_col" id="Products">
                            <h3>Services&nbsp;<span class="fas fa-caret-down" style="color: aliceblue;"></span></h3>
                            
                              <div class="links msab">
    
                               <a href="#">Illustration</a>
                               <a href="#">LBYH app Learning</a>
                               <a href="#">Sessions</a>
                               <a href="#">Trend</a>
                               
                            </div>
                         </div>
                      <div class="cus_col" id="links">
                         <h3>Quick Links&nbsp;<span class="fas fa-caret-down" style="color: aliceblue;"></span></h3>
                         
                          <div class="links msab">
    
                            <a href="#">About</a>
                            <a href="#">Services</a>
                            <a href="#">Our Policy</a>
                            <a href="#">Help</a>
                         </div>
                      </div>
                      <div class="cus_col" id="contact">
                          <h3>Contact Us&nbsp;<span class="fas fa-caret-down" style="color: aliceblue;"></span></h3>
                          <div class="links msab">
                            <div class="contact-details">
                              <i class="fa fa-location-dot"></i>
                              <p>Nawab City, Lucknow</p>
                            </div>
                            <div class="contact-details">
                              <i class="fa fa-envelope"></i>
                              <p>lbnh@gmail.com</p>
                            </div>
                            <div class="contact-details">
                              <i class="fa fa-phone"></i>
                              <p>+1-8745734367</p>
                            </div>
                          </div>
                      </div>
                </div>
                <div class="copyright">
                    &copy; Copyright@2024 LBYH-CBSE All rights reserved.
                </div>
            </div>
         </footer>
    </div>

    {% block js %}
    {% endblock %}
</body>
</html>